- name: Install Certbot
  yum:
    name:
      - epel-release
      - certbot
    state: present

- name: Generate Let's Encrypt certificate
  shell: |
    certbot certonly --standalone --agree-tos --non-interactive \
      -m {{ server_admin }} -d {{ server_name }}

- name: Add SSL to Apache (optional update vhost if needed)
  lineinfile:
    path: /etc/httpd/conf.d/vhost.conf
    line: "SSLCertificateFile /etc/letsencrypt/live/{{ server_name }}/fullchain.pem"
    insertafter: EOF
  notify: Restart Apache
